# https://github.com/golangci/golangci-lint#config-file

run:
  skip-files:
    - pkg/commit/commit.go
  modules-download-mode: vendor

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 40
  maligned:
    suggest-new: true
  dupl:
    threshold: 150
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  funlen:
    lines: 70
    statements: 50
  goimports:
    local-prefixes: github.com/o2gy84
  gocritic:
    enabled-tags:
      - style
    disabled-checks:
      - wrapperFunc
      - emptyStringTest
linters:
  disable-all: true
  enable:
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - gocognit
    - gochecknoglobals
    - dupl
    - interfacer 

  # Do not enable:
  # - wsl              (too opinionated)
  # - godox            (todos are OK)
  # - bodyclose        (false positives on helper functions)
  # - prealloc         (not worth it)
  # - maligned         (same as prealloc)

issues:
  exclude:
    - '`_msgpack` is unused'
    - '\`req\` is unused'
    - '\`opt\` is unused'
    - '`ctx` is unused'
    - 'result .+error.+ is always nil'
    - '`(version|buildNumber)` is unused'

  exclude-rules:
    # We don't care about function len in tests and binaries.
    - linters: [funlen]
      path: "(_test|main)\\.go"
    - linters: [scopelint, gocyclo]
      path: "_test\\.go"
    # Allow shadowing of "err".
    - linters: [govet]
      text: 'shadow: declaration of "err" shadows declaration'

