export GO111MODULE=on
export GOFLAGS=-mod=vendor

COMMIT ?= $(shell git log -n1 --pretty=format:"sha: %h, author: %an, commit: %s, date: %ai")


all: commit o2db

commit:
	@echo 'package commit' > pkg/commit/commit.go
	@echo "const Commit=\"${COMMIT}\"" >> pkg/commit/commit.go

o2db: commit
	go build -o bin/o2db github.com/o2gy84/o2db/cmd/o2db

clean:
	rm -rf bin

vet:
	go vet ./...

lint:
	golangci-lint run --deadline 10m

test:
	go test ./...

deps:
	GOFLAGS="" go mod tidy && go mod vendor

.PHONY: clean vet all test o2db

